export const A_ADD_PRODUCT = "A_ADD_PRODUCT";
export const A_GET_PRODUCTS = "A_GET_PRODUCTS";
export const A_CHANGE_PRODUCT = "A_CHANGE_PRODUCT";
export const A_DELETE_PRODUCT = "A_DELETE_PRODUCT";